language: go

os:
        - linux

group: travis_lts

go:
        - "1.16"
        - "1.17"
        - "1.18"
install:
        - go get golang.org/x/lint/golint
        - go get github.com/jgautheron/goconst/cmd/goconst
        - go get github.com/mdempsky/unconvert
        - go get github.com/mattn/goveralls
        - go get golang.org/x/tools/cmd/cover

script:
        - $HOME/gopath/bin/goveralls -service=travis-ci
        - test -z "$(go fmt ./...)"
        - test -z "$(go vet ./...)"
        - test -z "$(golint)"
        - test -z "$(goconst .)"
        - go test -test.v .
        - go test -test.v -race .
